Lab6
tonujet/nodejs-labs pull request #5
Opened 2023-05-18 15:39 UTC by tonujet

Воробей Антон ІА-11
Лабораторна робота №5
Як працює асинхронне апі ОС конектів до бази даних? В моєму представлені коли ми хостимо сервер, і на ньому поступово асинхронно обробляються реквести, то всі вони використовують один конекшин до бд. Чи може по цьому конекшину виконуватися звернення до бд від багатьох юзерів? Чи все таки кожному юзеру окремо відкривається конект і там вже проходить взаємодія. 
Виникло таке запитання, бо в тій же джаві ми використовуємо пул конекшинів і такі з'єднання одночасно може користуватися лише один поток.

2023-05-20 15:58 UTC, nosovk commented
в nodejs тоже есть пулл конекшенов, и можно использовать его для асинхронной работы с запросами. Если использовать один коннект - то да, запросы станут в очередь

2023-05-20 15:59 UTC, nosovk commented on Lab6/package.json
> +    "got": "^12.6.0",
потерял актуальность. Сейчас внутрь ноды строен undici
https://www.npmjs.com/package/undici
или можно его напрямую установить

2023-05-20 16:00 UTC, nosovk commented on Lab6/src/common/interface/repository/user/IUser.repository.ts
> +import {BriefVideoDto} from "../../../../dto/video/brief.video.dto.js";
когда ../../../ встречается, это как бы намекает что так делать не ок
@dto/video...
посмотреть на ts path aliases

2023-05-20 16:03 UTC, nosovk commented on Lab6/src/common/interface/repository/video/IVideo.repository.ts
> +export interface IVideoRepository {
на самом деле все эти интерфейсы тут не нужны. Но вот просто так это не обяснить. Современные языки умеют выводить типы (infer), и писать руками интерфейсы одноразовые нет необходимости. При этом это не уменьшает типизируемости кода, но при этом нет кучи лишней писанины. Фактически с точки зрения TS одноразовые интерфейсы не нужны обычно (если это не библиотека компонент)

2023-05-20 16:03 UTC, nosovk commented on Lab6/src/common/interface/repository/video/IVideo.repository.ts
> +export interface IVideoRepository {
для понимания стоит почитать примеры использования ts внтури nestjs к примеру (только на typeorm смотреть не нужно).

2023-05-20 16:05 UTC, nosovk commented on Lab6/src/db.config.ts
> +const client = new pg.Client({
https://node-postgres.com/apis/pool

2023-05-20 16:08 UTC, nosovk commented on Lab6/src/common/enum/db/tablenames.enum.ts
> +export enum TablenamesEnum {
https://www.typescriptlang.org/docs/handbook/enums.html#const-enums

2023-05-20 16:12 UTC, nosovk commented on Lab6/package.json
> +    "got": "^12.6.0",
внтури него кстати есть обычный fetch: undici.fetch

2023-05-20 16:12 UTC, tonujet commented on Lab6/src/common/interface/repository/user/IUser.repository.ts
> +import {BriefVideoDto} from "../../../../dto/video/brief.video.dto.js";
Краще використовувати аліаси, чи також можна обійтися реіпортами?

2023-05-20 16:13 UTC, nosovk commented on Lab6/src/repository/video/video.repository.ts
> +                LIMIT 10;
вот такие вещи ъорошо в параметры выносить

2023-05-20 16:14 UTC, nosovk commented on Lab6/src/repository/video/video.repository.ts
> +                     FROM ${this.tablename} v
подстановка интерполяцией в сам текст запроса - это безусловное зло. Так делать нельзя, т.к. это приводит потеницально к CVE и прочим проблемам.
В библиотеке для зарпосов к бд есть штатный метод подставноки параметров в запрос, который и экранирование и защитит от выстела в ногу

2023-05-20 16:15 UTC, nosovk commented on Lab6/src/repository/channel/channel.repository.ts
> +            WHERE c.id = '${id}'
вот тут тоже подстановка парметра прямо в запрос

2023-05-20 16:16 UTC, tonujet commented on Lab6/src/common/interface/repository/video/IVideo.repository.ts
> +export interface IVideoRepository {
Просто хотів все зробити по пятому принципу soliD,  тому і вирішив розділити рівні в архітектурі за допомогою ітерфейсів.

2023-05-20 16:17 UTC, nosovk requested changes
@ipiwebtech возможно не нужно давать людям больше typescript. Сделанно много работы, но она вся бесполезная из-за отсутвия понимания зачем он нужен. Я не знаю как просто пояснить что тут больше половины можно выкинуть и станет лучше. Возможно если бы у человека не было опыта с java ранее - было бы проще.

2023-05-28 14:46 UTC, nosovk commented on Lab6/src/common/interface/repository/video/IVideo.repository.ts
> +export interface IVideoRepository {
тут ошибка новичка похоже - D тебе нужен на уровне модулей, а у тебя для всего там интерфейсы есть. То есть понятно что ты интерфейсы можешь написать, но смысла в них нет, т.к. они никогда не понадобятся

2023-05-28 14:49 UTC, nosovk approved these changes
@ipiwebtech тут можно поставить хорошую оценку, потому что прямо большая работа проделана в улучшении с начальной версии до текущей (надTS особенно)

2023-06-17 22:42 UTC, merged